import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SectionContainer from '@/components/SectionContainer'
import clsx from 'clsx'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, 'antialiased', 'text-[8px] lg:text-[12px]')}>
        <SectionContainer>{children}</SectionContainer>
      </body>
    </html>
  )
}
